"""empty message

Revision ID: 0c7d2004b225
Revises: 7e3b87e0b165
Create Date: 2021-12-12 14:05:48.897906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7d2004b225'
down_revision = '7e3b87e0b165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('document_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'judgments', 'pleading_documents', ['document_url'], ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_column('judgments', 'document_url')
    # ### end Alembic commands ###
