"""empty message

Revision ID: 1628eb05c573
Revises: 2d80f8ef6f25
Create Date: 2021-06-02 23:06:24.825642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1628eb05c573'
down_revision = '2d80f8ef6f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgments',
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('in_favor_of_id', sa.Integer(), nullable=True),
                    sa.Column('claims_possession',
                              sa.Boolean(), nullable=True),
                    sa.Column('claims_fees', sa.Numeric(
                        scale=2), nullable=True),
                    sa.Column('entered_by_id', sa.Integer(), nullable=True),
                    sa.Column('interest', sa.Boolean(), nullable=True),
                    sa.Column('interest_rate', sa.Numeric(), nullable=True),
                    sa.Column('interest_follows_site',
                              sa.Boolean(), nullable=True),
                    sa.Column('dismissal_basis_id',
                              sa.Integer(), nullable=True),
                    sa.Column('with_prejudice', sa.Boolean(), nullable=True),
                    sa.Column('notes', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_column('detainer_warrants', 'judgment_notes')
    op.drop_column('detainer_warrants', 'judgment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('judgment_id', sa.INTEGER(
    ), server_default=sa.text('4'), autoincrement=False, nullable=False))
    op.add_column('detainer_warrants', sa.Column('judgment_notes',
                  sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('judgments')
    # ### end Alembic commands ###
