"""empty message

Revision ID: 168409f5e2eb
Revises: 771c1e2133a1
Create Date: 2021-11-16 00:39:45.025912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168409f5e2eb'
down_revision = '771c1e2133a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('last_pleading_documents_check', sa.DateTime(), nullable=True))
    op.add_column('detainer_warrants', sa.Column('pleading_document_check_was_successful', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detainer_warrants', 'pleading_document_check_was_successful')
    op.drop_column('detainer_warrants', 'last_pleading_documents_check')
    # ### end Alembic commands ###
