"""empty message

Revision ID: 243c813807f4
Revises: d5ce46575091
Create Date: 2021-04-04 09:14:04.016890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243c813807f4'
down_revision = 'd5ce46575091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('nonpayment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detainer_warrants', 'nonpayment')
    # ### end Alembic commands ###
