"""empty message

Revision ID: 2cb6c179bae9
Revises: d30568c05df2
Create Date: 2021-09-21 11:28:19.404240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb6c179bae9'
down_revision = 'd30568c05df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('defendants_first_name_middle_name_last_name_suffix_address__key', 'defendants', type_='unique')
    op.create_unique_constraint(None, 'defendants', ['first_name', 'middle_name', 'last_name', 'suffix', 'address', 'district_id', 'potential_phones'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defendants', type_='unique')
    op.create_unique_constraint('defendants_first_name_middle_name_last_name_suffix_address__key', 'defendants', ['first_name', 'middle_name', 'last_name', 'suffix', 'address', 'district_id'])
    # ### end Alembic commands ###
