"""empty message

Revision ID: 4ca3c372fc77
Revises: 6ff719bc718a
Create Date: 2022-01-14 23:29:52.071398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca3c372fc77'
down_revision = '6ff719bc718a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearings', sa.Column(
        'court_order_number', sa.Integer(), nullable=True))
    op.drop_column('judgments', 'court_order_number')
    op.drop_column('judgments', 'court_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column(
        'court_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('court_order_number',
                  sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('hearings', 'court_order_number')
    # ### end Alembic commands ###
