"""empty message

Revision ID: 537789537d2a
Revises: bed93a6f57fa
Create Date: 2021-07-07 21:52:03.917318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537789537d2a'
down_revision = 'bed93a6f57fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column(
        'court_date', sa.Date(), nullable=True))
    op.add_column('judgments', sa.Column(
        'courtroom_id', sa.Integer(), nullable=True))
    op.add_column('judgments', sa.Column('defendant_address',
                  sa.String(length=255), nullable=True))
    op.add_column('judgments', sa.Column(
        'defendant_attorney_id', sa.Integer(), nullable=True))
    op.add_column('judgments', sa.Column(
        'mediation_letter', sa.Boolean(), nullable=True))
    op.add_column('judgments', sa.Column(
        'plaintiff_attorney_id', sa.Integer(), nullable=True))
    op.add_column('judgments', sa.Column(
        'plaintiff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'judgments', 'attorneys', [
                          'plaintiff_attorney_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'judgments', 'plaintiffs', [
                          'plaintiff_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'judgments', 'courtrooms', [
                          'courtroom_id'], ['id'])
    op.create_foreign_key(None, 'judgments', 'attorneys', [
                          'defendant_attorney_id'], ['id'], ondelete='CASCADE')
    op.drop_column('judgments', 'file_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('file_date', sa.DATE(), server_default=sa.text(
        "'2021-07-05'::date"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_column('judgments', 'plaintiff_id')
    op.drop_column('judgments', 'plaintiff_attorney_id')
    op.drop_column('judgments', 'mediation_letter')
    op.drop_column('judgments', 'defendant_attorney_id')
    op.drop_column('judgments', 'defendant_address')
    op.drop_column('judgments', 'courtroom_id')
    op.drop_column('judgments', 'court_date')
    # ### end Alembic commands ###
