"""empty message

Revision ID: 5ea709a8632b
Revises: eeeef5e2ea07
Create Date: 2022-02-12 10:07:49.601754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea709a8632b'
down_revision = 'eeeef5e2ea07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('audit_status_id', sa.Integer(), nullable=True))
    op.drop_column('cases', 'zip_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('cases', 'audit_status_id')
    # ### end Alembic commands ###
