"""empty message

Revision ID: 611584f72ec8
Revises: 2cb6c179bae9
Create Date: 2021-10-08 15:58:30.728134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611584f72ec8'
down_revision = '2cb6c179bae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detainer_warrants_presiding_judge_id_fkey', 'detainer_warrants', type_='foreignkey')
    op.drop_constraint('detainer_warrants_courtroom_id_fkey', 'detainer_warrants', type_='foreignkey')
    op.drop_column('detainer_warrants', 'court_date')
    op.drop_column('detainer_warrants', 'presiding_judge_id')
    op.drop_column('detainer_warrants', 'courtroom_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('courtroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('detainer_warrants', sa.Column('presiding_judge_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('detainer_warrants', sa.Column('court_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('detainer_warrants_courtroom_id_fkey', 'detainer_warrants', 'courtrooms', ['courtroom_id'], ['id'])
    op.create_foreign_key('detainer_warrants_presiding_judge_id_fkey', 'detainer_warrants', 'judges', ['presiding_judge_id'], ['id'])
    # ### end Alembic commands ###
