"""empty message

Revision ID: 6ff719bc718a
Revises: 141b8f6f15e2
Create Date: 2022-01-14 17:33:47.320821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff719bc718a'
down_revision = '141b8f6f15e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('judgments_courtroom_id_fkey', 'judgments', type_='foreignkey')
    op.drop_column('judgments', 'courtroom_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('courtroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('judgments_courtroom_id_fkey', 'judgments', 'courtrooms', ['courtroom_id'], ['id'])
    # ### end Alembic commands ###
