"""empty message

Revision ID: 7550c541dbc5
Revises: 007864c7fca9
Create Date: 2021-03-16 14:13:00.562718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7550c541dbc5'
down_revision = '007864c7fca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defendants', sa.Column(
        'potential_phones', sa.String(length=255), nullable=True))
    op.alter_column('defendants', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.add_column('detainer_warrants', sa.Column(
        'is_cares', sa.Boolean(), nullable=True))
    op.add_column('detainer_warrants', sa.Column(
        'is_legacy', sa.Boolean(), nullable=True))
    op.add_column('detainer_warrants', sa.Column('judgment_id',
                                                 sa.Integer(), nullable=False, server_default=sa.text('4')))
    op.add_column('detainer_warrants', sa.Column(
        'zip_code', sa.String(length=10), nullable=True))
    op.drop_column('detainer_warrants', 'judgment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column(
        'judgment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('detainer_warrants', 'zip_code')
    op.drop_column('detainer_warrants', 'judgment_id')
    op.drop_column('detainer_warrants', 'is_legacy')
    op.drop_column('detainer_warrants', 'is_cares')
    op.alter_column('defendants', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.drop_column('defendants', 'potential_phones')
    # ### end Alembic commands ###
