"""empty message

Revision ID: 771c1e2133a1
Revises: bef0228518e5
Create Date: 2021-11-12 16:09:14.969895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771c1e2133a1'
down_revision = 'bef0228518e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pleading_documents',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('kind_id', sa.Integer(), nullable=True),
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['detainer_warrants.docket_id'], ),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pleading_documents')
    # ### end Alembic commands ###
