"""empty message

Revision ID: 776d55aeea90
Revises: fdb6e0382ac5
Create Date: 2021-07-25 20:46:06.395056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776d55aeea90'
down_revision = 'fdb6e0382ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column(
        'last_edited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'judgments', 'user', [
                          'last_edited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_column('judgments', 'last_edited_by_id')
    # ### end Alembic commands ###
