"""empty message

Revision ID: 7e3b87e0b165
Revises: 8e9da43143f4
Create Date: 2021-12-07 00:19:16.284191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b87e0b165'
down_revision = '8e9da43143f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column(
        'file_date', sa.Date(), nullable=True))
    # op.alter_column('judgments', 'hearing_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('judgments', 'hearing_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_column('judgments', 'file_date')
    # ### end Alembic commands ###
