"""empty message

Revision ID: 88ce4e07559c
Revises: 9e1a31395f60
Create Date: 2021-03-31 15:24:20.127027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ce4e07559c'
down_revision = '9e1a31395f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvass_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvass_warrants',
    sa.Column('canvass_event.id', sa.Integer(), nullable=False),
    sa.Column('detainer_warrant_docket_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['canvass_event.id'], ['canvass_events.id'], ),
    sa.ForeignKeyConstraint(['detainer_warrant_docket_id'], ['detainer_warrants.docket_id'], ),
    sa.PrimaryKeyConstraint('canvass_event.id', 'detainer_warrant_docket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canvass_warrants')
    op.drop_table('canvass_events')
    # ### end Alembic commands ###
