"""empty message

Revision ID: 8e9da43143f4
Revises: 3f0b77aced75
Create Date: 2021-12-06 19:43:55.343621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9da43143f4'
down_revision = '3f0b77aced75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('''
    # INSERT INTO hearings (court_date, address, docket_id, courtroom_id, plaintiff_id, plaintiff_attorney_id, defendant_attorney_id)
    # SELECT court_date, 'unknown', detainer_warrant_id, courtroom_id, plaintiff_id, plaintiff_attorney_id, defendant_attorney_id
    # FROM judgments
    # WHERE judgments.court_date <> NULL;
    # ''')
    op.add_column('judgments', sa.Column(
        'hearing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'judgments', 'hearings',
                          ['hearing_id'], ['id'])
    # op.execute('''
    # UPDATE judgments
    # SET hearing_id = hearings.id
    # FROM hearings
    # WHERE judgments.detainer_warrant_id = hearings.docket_id;
    # ''')
    # op.alter_column('judgments', 'hearing_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('judgments_hearing_id_fkey',
                       'judgments', type_='foreignkey')
    op.drop_column('judgments', 'hearing_id')
    # ### end Alembic commands ###
