"""empty message

Revision ID: 901cb1f2bbc4
Revises: 124241fed961
Create Date: 2021-04-04 08:50:16.629012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901cb1f2bbc4'
down_revision = '124241fed961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detainer_warrant_defendants_detainer_warrant_docket_id_fkey', 'detainer_warrant_defendants', type_='foreignkey')
    op.drop_constraint('detainer_warrant_defendants_defendant_id_fkey', 'detainer_warrant_defendants', type_='foreignkey')
    op.create_foreign_key(None, 'detainer_warrant_defendants', 'detainer_warrants', ['detainer_warrant_docket_id'], ['docket_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detainer_warrant_defendants', 'defendants', ['defendant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detainer_warrant_defendants', type_='foreignkey')
    op.drop_constraint(None, 'detainer_warrant_defendants', type_='foreignkey')
    op.create_foreign_key('detainer_warrant_defendants_defendant_id_fkey', 'detainer_warrant_defendants', 'defendants', ['defendant_id'], ['id'])
    op.create_foreign_key('detainer_warrant_defendants_detainer_warrant_docket_id_fkey', 'detainer_warrant_defendants', 'detainer_warrants', ['detainer_warrant_docket_id'], ['docket_id'])
    # ### end Alembic commands ###
