"""empty message

Revision ID: 978fc20cdb0c
Revises: 19bc2460d32b
Create Date: 2021-11-19 18:02:36.009550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978fc20cdb0c'
down_revision = '19bc2460d32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'notes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
