"""empty message

Revision ID: 9e1a31395f60
Revises: aa989b9b2862
Create Date: 2021-03-29 20:28:32.992434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1a31395f60'
down_revision = 'aa989b9b2862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defendant_phone_verifications')
    op.add_column('defendants', sa.Column('verified_phone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'defendants', 'phone_number_verifications', ['verified_phone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defendants', type_='foreignkey')
    op.drop_column('defendants', 'verified_phone_id')
    op.create_table('defendant_phone_verifications',
    sa.Column('defendant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_number_verification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['defendant_id'], ['defendants.id'], name='defendant_phone_verifications_defendant_id_fkey'),
    sa.ForeignKeyConstraint(['phone_number_verification_id'], ['phone_number_verifications.id'], name='defendant_phone_verifications_phone_number_verification_id_fkey'),
    sa.PrimaryKeyConstraint('defendant_id', 'phone_number_verification_id', name='defendant_phone_verifications_pkey')
    )
    # ### end Alembic commands ###
