"""empty message

Revision ID: a5ced3885cae
Revises: 905a870dfffb
Create Date: 2021-04-08 10:48:13.874922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ced3885cae'
down_revision = '905a870dfffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detainer_warrants', 'amount_claimed_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detainer_warrants', 'amount_claimed_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
