"""add uniqueness pairs with district

Revision ID: a72b9feecf0d
Revises: 776d55aeea90
Create Date: 2021-07-28 18:37:54.655073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72b9feecf0d'
down_revision = '776d55aeea90'
branch_labels = None
depends_on = None

pair = ['name', 'district_id']
names = ['first_name', 'middle_name', 'last_name',
         'suffix', 'district_id', 'potential_phones']


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "attorneys", pair)
    op.create_unique_constraint(None, "plaintiffs", pair)
    op.create_unique_constraint(None, "judges", pair)
    op.create_unique_constraint(
        None, "defendants", names)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "attorneys", pair)
    op.drop_constraint(None, "plaintiffs", pair)
    op.drop_constraint(None, "judges", pair)
    op.drop_constraint(None, "defendants", names)
    # ### end Alembic commands ###
