"""empty message

Revision ID: b46df45c94ec
Revises: 978fc20cdb0c
Create Date: 2021-11-19 20:12:07.103131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46df45c94ec'
down_revision = '978fc20cdb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgements', sa.Column('_continuance_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judgements', '_continuance_on')
    # ### end Alembic commands ###
