"""empty message

Revision ID: bcf853c67790
Revises: f30cc5d13b95
Create Date: 2021-08-03 19:26:35.440576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf853c67790'
down_revision = 'f30cc5d13b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('districts_name_key', 'districts', type_='unique')
    op.add_column('judgements', sa.Column('court_order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judgements', 'court_order_number')
    op.create_unique_constraint('districts_name_key', 'districts', ['name'])
    # ### end Alembic commands ###
