"""empty message

Revision ID: bed93a6f57fa
Revises: a55bba2464ba
Create Date: 2021-07-07 09:17:06.805435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed93a6f57fa'
down_revision = 'a55bba2464ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgements', sa.Column('judge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'judgements', 'judges', ['judge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judgements', type_='foreignkey')
    op.drop_column('judgements', 'judge_id')
    # ### end Alembic commands ###
