"""empty message

Revision ID: bfe5032cbec7
Revises: 107428217fd0
Create Date: 2021-12-27 18:23:44.457188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe5032cbec7'
down_revision = '107428217fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pleading_documents', sa.Column('status_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pleading_documents', 'status_id')
    # ### end Alembic commands ###
