"""empty message

Revision ID: c2aa210b1c8a
Revises: cbe1b0d2da6d
Create Date: 2021-03-11 01:51:15.021809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2aa210b1c8a'
down_revision = 'cbe1b0d2da6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detainer_warrants', 'court_date',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detainer_warrants', 'court_date',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
