"""empty message

Revision ID: c727cd529fcc
Revises: 4ca3c372fc77
Create Date: 2022-01-20 00:22:34.504920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c727cd529fcc'
down_revision = '4ca3c372fc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('detainer_warrant_addresses',
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.text'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docket_id'], ['cases.docket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docket_id', 'address_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detainer_warrant_addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
