"""empty message

Revision ID: cbe1b0d2da6d
Revises: d50acc39df14
Create Date: 2021-03-11 01:50:15.336032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe1b0d2da6d'
down_revision = 'd50acc39df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('amount_claimed_category_id', sa.Integer(), nullable=False))
    op.add_column('detainer_warrants', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_column('detainer_warrants', 'status')
    op.drop_column('detainer_warrants', 'amount_claimed_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('amount_claimed_category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('detainer_warrants', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('detainer_warrants', 'status_id')
    op.drop_column('detainer_warrants', 'amount_claimed_category_id')
    # ### end Alembic commands ###
