"""empty message

Revision ID: cfcfe270c1b4
Revises: 7ce0170b25d2
Create Date: 2021-03-16 22:53:18.846778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcfe270c1b4'
down_revision = '7ce0170b25d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_number_verifications', sa.Column('caller_type_id', sa.Integer(), nullable=True))
    op.drop_column('phone_number_verifications', 'caller_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_number_verifications', sa.Column('caller_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('phone_number_verifications', 'caller_type_id')
    # ### end Alembic commands ###
