"""empty message

Revision ID: d18638099caf
Revises: b46df45c94ec
Create Date: 2021-11-19 21:46:48.739687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18638099caf'
down_revision = 'b46df45c94ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pleading_document_check_mismatched_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'pleading_document_check_mismatched_html')
    # ### end Alembic commands ###
