"""empty message

Revision ID: d5ce46575091
Revises: ac5be2b66a99
Create Date: 2021-04-04 09:08:01.174418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ce46575091'
down_revision = 'ac5be2b66a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('court_date_recurring_id', sa.Integer(), nullable=True))
    op.drop_column('detainer_warrants', 'court_date_notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('court_date_notes', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('detainer_warrants', 'court_date_recurring_id')
    # ### end Alembic commands ###
