"""empty message

Revision ID: d6aa4166a022
Revises: 7550c541dbc5
Create Date: 2021-03-16 15:55:19.387166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6aa4166a022'
down_revision = '7550c541dbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('court_date_notes', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detainer_warrants', 'court_date_notes')
    # ### end Alembic commands ###
