"""empty message

Revision ID: d6e31f9483cd
Revises: bcf853c67790
Create Date: 2021-08-20 15:06:39.824286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e31f9483cd'
down_revision = 'bcf853c67790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attorneys', sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False))
    op.add_column('defendants', sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False))
    op.add_column('judges', sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False))
    op.add_column('plaintiffs', sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaintiffs', 'aliases')
    op.drop_column('judges', 'aliases')
    op.drop_column('defendants', 'aliases')
    op.drop_column('attorneys', 'aliases')
    # ### end Alembic commands ###
