"""empty message

Revision ID: d7adb53b80a7
Revises: 
Create Date: 2024-04-30 10:27:43.231798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7adb53b80a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courtrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_number_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('caller_type_id', sa.Integer(), nullable=True),
    sa.Column('name_error_code', sa.Integer(), nullable=True),
    sa.Column('carrier_error_code', sa.Integer(), nullable=True),
    sa.Column('mobile_country_code', sa.String(length=10), nullable=True),
    sa.Column('mobile_network_code', sa.String(length=10), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('phone_type', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('national_format', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('plaintiffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_navigation_id', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('cases',
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.BigInteger(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_attorney_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address_certainty', sa.Float(), nullable=True),
    sa.Column('court_date_recurring_id', sa.Integer(), nullable=True),
    sa.Column('amount_claimed', sa.Numeric(scale=2), nullable=True),
    sa.Column('claims_possession', sa.Boolean(), nullable=True),
    sa.Column('is_cares', sa.Boolean(), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=True),
    sa.Column('nonpayment', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('last_pleading_documents_check', sa.DateTime(), nullable=True),
    sa.Column('pleading_document_check_was_successful', sa.Boolean(), nullable=True),
    sa.Column('pleading_document_check_mismatched_html', sa.Text(), nullable=True),
    sa.Column('last_edited_by_id', sa.Integer(), nullable=True),
    sa.Column('audit_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_url'], ['pleading_documents.url'], name='cases_document_url_fkey', use_alter=True),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_attorney_id'], ['attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['plaintiffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docket_id')
    )
    op.create_table('defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('suffix', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False),
    sa.Column('potential_phones', sa.String(length=255), nullable=True),
    sa.Column('verified_phone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verified_phone_id'], ['phone_number_verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'middle_name', 'last_name', 'suffix', 'potential_phones')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('canvass_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detainer_warrant_addresses',
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.text'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docket_id'], ['cases.docket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docket_id', 'address_id')
    )
    op.create_table('detainer_warrant_defendants',
    sa.Column('detainer_warrant_docket_id', sa.String(length=255), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defendant_id'], ['defendants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detainer_warrant_docket_id'], ['cases.docket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detainer_warrant_docket_id', 'defendant_id')
    )
    op.create_table('events_users',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_date', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('court_order_number', sa.Integer(), nullable=True),
    sa.Column('continuance_on', sa.Date(), nullable=True),
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.Column('courtroom_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_attorney_id', sa.Integer(), nullable=True),
    sa.Column('defendant_attorney_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['courtroom_id'], ['courtrooms.id'], ),
    sa.ForeignKeyConstraint(['defendant_attorney_id'], ['attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docket_id'], ['cases.docket_id'], ),
    sa.ForeignKeyConstraint(['plaintiff_attorney_id'], ['attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['plaintiffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_date', 'docket_id')
    )
    op.create_table('phone_bank_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pleading_documents',
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('kind_id', sa.Integer(), nullable=True),
    sa.Column('docket_id', sa.String(length=255), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['cases.docket_id'], ),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('canvass_warrants',
    sa.Column('canvass_event.id', sa.Integer(), nullable=False),
    sa.Column('detainer_warrant_docket_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['canvass_event.id'], ['canvass_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detainer_warrant_docket_id'], ['cases.docket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('canvass_event.id', 'detainer_warrant_docket_id')
    )
    op.create_table('hearing_defendants',
    sa.Column('hearing_id', sa.Integer(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defendant_id'], ['defendants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hearing_id'], ['hearings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hearing_id', 'defendant_id')
    )
    op.create_table('judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_favor_of_id', sa.Integer(), nullable=True),
    sa.Column('awards_possession', sa.Boolean(), nullable=True),
    sa.Column('awards_fees', sa.Numeric(scale=2), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.Column('interest', sa.Boolean(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(), nullable=True),
    sa.Column('interest_follows_site', sa.Boolean(), nullable=True),
    sa.Column('dismissal_basis_id', sa.Integer(), nullable=True),
    sa.Column('with_prejudice', sa.Boolean(), nullable=True),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('mediation_letter', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hearing_id', sa.Integer(), nullable=True),
    sa.Column('detainer_warrant_id', sa.String(length=255), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_attorney_id', sa.Integer(), nullable=True),
    sa.Column('defendant_attorney_id', sa.Integer(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('last_edited_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defendant_attorney_id'], ['attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detainer_warrant_id'], ['cases.docket_id'], ),
    sa.ForeignKeyConstraint(['document_url'], ['pleading_documents.url'], ),
    sa.ForeignKeyConstraint(['hearing_id'], ['hearings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_attorney_id'], ['attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['plaintiffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_bank_tenants',
    sa.Column('phone_bank_event_id', sa.Integer(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defendant_id'], ['defendants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_bank_event_id'], ['phone_bank_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_bank_event_id', 'defendant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_bank_tenants')
    op.drop_table('judgments')
    op.drop_table('hearing_defendants')
    op.drop_table('canvass_warrants')
    op.drop_table('pleading_documents')
    op.drop_table('phone_bank_events')
    op.drop_table('hearings')
    op.drop_table('events_users')
    op.drop_table('detainer_warrant_defendants')
    op.drop_table('detainer_warrant_addresses')
    op.drop_table('canvass_events')
    op.drop_table('roles_users')
    op.drop_table('events')
    op.drop_table('defendants')
    op.drop_table('cases')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('plaintiffs')
    op.drop_table('phone_number_verifications')
    op.drop_table('judges')
    op.drop_table('courtrooms')
    op.drop_table('campaigns')
    op.drop_table('attorneys')
    op.drop_table('addresses')
    # ### end Alembic commands ###
