"""empty message

Revision ID: dafb40b232f1
Revises: 1628eb05c573
Create Date: 2021-06-02 23:09:35.663733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafb40b232f1'
down_revision = '1628eb05c573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('detainer_warrant_id',
                  sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'judgments', 'detainer_warrants', [
                          'detainer_warrant_id'], ['docket_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'judgments', type_='foreignkey')
    op.drop_column('judgments', 'detainer_warrant_id')
    # ### end Alembic commands ###
