"""empty message

Revision ID: e3a668a93cbe
Revises: 5ea709a8632b
Create Date: 2022-02-26 13:49:16.177047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a668a93cbe'
down_revision = '5ea709a8632b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('address_certainty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'address_certainty')
    # ### end Alembic commands ###
