"""empty message

Revision ID: f93dd565c935
Revises: 056242d18e05
Create Date: 2021-12-14 21:50:51.538471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93dd565c935'
down_revision = '056242d18e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearings', sa.Column('continuance_on', sa.Date(), nullable=True))
    op.drop_column('judgments', '_continuance_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('_continuance_on', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('hearings', 'continuance_on')
    # ### end Alembic commands ###
