"""empty message

Revision ID: fcb1a02a41e9
Revises: 901cb1f2bbc4
Create Date: 2021-04-04 08:52:26.564998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb1a02a41e9'
down_revision = '901cb1f2bbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('canvass_warrants_detainer_warrant_docket_id_fkey', 'canvass_warrants', type_='foreignkey')
    op.drop_constraint('canvass_warrants_canvass_event.id_fkey', 'canvass_warrants', type_='foreignkey')
    op.create_foreign_key(None, 'canvass_warrants', 'detainer_warrants', ['detainer_warrant_docket_id'], ['docket_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'canvass_warrants', 'canvass_events', ['canvass_event.id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'canvass_warrants', type_='foreignkey')
    op.drop_constraint(None, 'canvass_warrants', type_='foreignkey')
    op.create_foreign_key('canvass_warrants_canvass_event.id_fkey', 'canvass_warrants', 'canvass_events', ['canvass_event.id'], ['id'])
    op.create_foreign_key('canvass_warrants_detainer_warrant_docket_id_fkey', 'canvass_warrants', 'detainer_warrants', ['detainer_warrant_docket_id'], ['docket_id'])
    # ### end Alembic commands ###
