"""empty message

Revision ID: fdb6e0382ac5
Revises: 74fdabe3d5a3
Create Date: 2021-07-25 20:13:03.136856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb6e0382ac5'
down_revision = '74fdabe3d5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detainer_warrants', sa.Column('last_edited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detainer_warrants', 'user', ['last_edited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detainer_warrants', type_='foreignkey')
    op.drop_column('detainer_warrants', 'last_edited_by_id')
    # ### end Alembic commands ###
