# SEARCH PAGE
DOCKET_NUMBER_INPUT = "P_21"
CASE_TYPE_SELECT = "P_31"
EXPORT_BUTTON = "WTKCB_8"
FILE_DATE_START_INPUT = "P_26"
FILE_DATE_END_INPUT = "P_27"
SEARCH_BUTTON = "WTKCB_20"

# DETAINER WARRANT PAGE
NEW_SEARCH_BUTTON = "WTKCB_111"
